#

var _mysql_to_java_charset = {
    'armscii8': 'NotImplementedError',
    'binary':   'ASCII',
    'dec8':     'NotImplementedError',
    'eucjpms':  'NotImplementedError',
    'geostd8':  'NotImplementedError',
    'hp8':      'NotImplementedError',
    'keybcs2':  'NotImplementedError',
    'koi8r':    'KOI8_R',
    'koi8u':    'KOI8_U',
    'macce':    'MacCentralEurope',
    'swe7':     'NotImplementedError',
    'ucs2':     'UnicodeBigUnmarked',
    'utf8mb4':  'UTF8',
    'utf16le':  'UnicodeLittleUnmarked',
    'utf16':    'UTF-16',
    'utf32':    'UTF_32BE'
};


var CHARSETS = {
    32: {id: 32,
                name: 'armscii8',
                collation: 'armscii8_general_ci',
                is_default: true,
                maxlen: 1},
    64: {id: 64,
                name: 'armscii8',
                collation: 'armscii8_bin',
                is_default: false,
                maxlen: 1},
    11: {id: 11,
                name: 'ascii',
                collation: 'ascii_general_ci',
                is_default: true,
                maxlen: 1},
    65: {id: 65,
                name: 'ascii',
                collation: 'ascii_bin',
                is_default: false,
                maxlen: 1},
    1: {id: 1,
               name: 'big5',
               collation: 'big5_chinese_ci',
               is_default: true,
               maxlen: 2},
    84: {id: 84,
                name: 'big5',
                collation: 'big5_bin',
                is_default: false,
                maxlen: 2},
    63: {id: 63,
                name: 'binary',
                collation: 'binary',
                is_default: true,
                maxlen: 1},
    26: {id: 26,
                name: 'cp1250',
                collation: 'cp1250_general_ci',
                is_default: true,
                maxlen: 1},
    34: {id: 34,
                name: 'cp1250',
                collation: 'cp1250_czech_cs',
                is_default: false,
                maxlen: 1},
    44: {id: 44,
                name: 'cp1250',
                collation: 'cp1250_croatian_ci',
                is_default: false,
                maxlen: 1},
    66: {id: 66,
                name: 'cp1250',
                collation: 'cp1250_bin',
                is_default: false,
                maxlen: 1},
    99: {id: 99,
                name: 'cp1250',
                collation: 'cp1250_polish_ci',
                is_default: false,
                maxlen: 1},
    14: {id: 14,
                name: 'cp1251',
                collation: 'cp1251_bulgarian_ci',
                is_default: false,
                maxlen: 1},
    23: {id: 23,
                name: 'cp1251',
                collation: 'cp1251_ukrainian_ci',
                is_default: false,
                maxlen: 1},
    50: {id: 50,
                name: 'cp1251',
                collation: 'cp1251_bin',
                is_default: false,
                maxlen: 1},
    51: {id: 51,
                name: 'cp1251',
                collation: 'cp1251_general_ci',
                is_default: true,
                maxlen: 1},
    52: {id: 52,
                name: 'cp1251',
                collation: 'cp1251_general_cs',
                is_default: false,
                maxlen: 1},
    57: {id: 57,
                name: 'cp1256',
                collation: 'cp1256_general_ci',
                is_default: true,
                maxlen: 1},
    67: {id: 67,
                name: 'cp1256',
                collation: 'cp1256_bin',
                is_default: false,
                maxlen: 1},
    29: {id: 29,
                name: 'cp1257',
                collation: 'cp1257_lithuanian_ci',
                is_default: false,
                maxlen: 1},
    58: {id: 58,
                name: 'cp1257',
                collation: 'cp1257_bin',
                is_default: false,
                maxlen: 1},
    59: {id: 59,
                name: 'cp1257',
                collation: 'cp1257_general_ci',
                is_default: true,
                maxlen: 1},
    4: {id: 4,
               name: 'cp850',
               collation: 'cp850_general_ci',
               is_default: true,
               maxlen: 1},
    80: {id: 80,
                name: 'cp850',
                collation: 'cp850_bin',
                is_default: false,
                maxlen: 1},
    40: {id: 40,
                name: 'cp852',
                collation: 'cp852_general_ci',
                is_default: true,
                maxlen: 1},
    81: {id: 81,
                name: 'cp852',
                collation: 'cp852_bin',
                is_default: false,
                maxlen: 1},
    36: {id: 36,
                name: 'cp866',
                collation: 'cp866_general_ci',
                is_default: true,
                maxlen: 1},
    68: {id: 68,
                name: 'cp866',
                collation: 'cp866_bin',
                is_default: false,
                maxlen: 1},
    95: {id: 95,
                name: 'cp932',
                collation: 'cp932_japanese_ci',
                is_default: true,
                maxlen: 2},
    96: {id: 96,
                name: 'cp932',
                collation: 'cp932_bin',
                is_default: false,
                maxlen: 2},
    3: {id: 3,
               name: 'dec8',
               collation: 'dec8_swedish_ci',
               is_default: true,
               maxlen: 1},
    69: {id: 69,
                name: 'dec8',
                collation: 'dec8_bin',
                is_default: false,
                maxlen: 1},
    97: {id: 97,
                name: 'eucjpms',
                collation: 'eucjpms_japanese_ci',
                is_default: true,
                maxlen: 3},
    98: {id: 98,
                name: 'eucjpms',
                collation: 'eucjpms_bin',
                is_default: false,
                maxlen: 3},
    19: {id: 19,
                name: 'euckr',
                collation: 'euckr_korean_ci',
                is_default: true,
                maxlen: 2},
    85: {id: 85,
                name: 'euckr',
                collation: 'euckr_bin',
                is_default: false,
                maxlen: 2},
    24: {id: 24,
                name: 'gb2312',
                collation: 'gb2312_chinese_ci',
                is_default: true,
                maxlen: 2},
    86: {id: 86,
                name: 'gb2312',
                collation: 'gb2312_bin',
                is_default: false,
                maxlen: 2},
    28: {id: 28,
                name: 'gbk',
                collation: 'gbk_chinese_ci',
                is_default: true,
                maxlen: 2},
    87: {id: 87,
                name: 'gbk',
                collation: 'gbk_bin',
                is_default: false,
                maxlen: 2},
    92: {id: 92,
                name: 'geostd8',
                collation: 'geostd8_general_ci',
                is_default: true,
                maxlen: 1},
    93: {id: 93,
                name: 'geostd8',
                collation: 'geostd8_bin',
                is_default: false,
                maxlen: 1},
    25: {id: 25,
                name: 'greek',
                collation: 'greek_general_ci',
                is_default: true,
                maxlen: 1},
    70: {id: 70,
                name: 'greek',
                collation: 'greek_bin',
                is_default: false,
                maxlen: 1},
    16: {id: 16,
                name: 'hebrew',
                collation: 'hebrew_general_ci',
                is_default: true,
                maxlen: 1},
    71: {id: 71,
                name: 'hebrew',
                collation: 'hebrew_bin',
                is_default: false,
                maxlen: 1},
    6: {id: 6,
               name: 'hp8',
               collation: 'hp8_english_ci',
               is_default: true,
               maxlen: 1},
    72: {id: 72,
                name: 'hp8',
                collation: 'hp8_bin',
                is_default: false,
                maxlen: 1},
    37: {id: 37,
                name: 'keybcs2',
                collation: 'keybcs2_general_ci',
                is_default: true,
                maxlen: 1},
    73: {id: 73,
                name: 'keybcs2',
                collation: 'keybcs2_bin',
                is_default: false,
                maxlen: 1},
    7: {id: 7,
               name: 'koi8r',
               collation: 'koi8r_general_ci',
               is_default: true,
               maxlen: 1},
    74: {id: 74,
                name: 'koi8r',
                collation: 'koi8r_bin',
                is_default: false,
                maxlen: 1},
    22: {id: 22,
                name: 'koi8u',
                collation: 'koi8u_general_ci',
                is_default: true,
                maxlen: 1},
    75: {id: 75,
                name: 'koi8u',
                collation: 'koi8u_bin',
                is_default: false,
                maxlen: 1},
    5: {id: 5,
               name: 'latin1',
               collation: 'latin1_german1_ci',
               is_default: false,
               maxlen: 1},
    8: {id: 8,
               name: 'latin1',
               collation: 'latin1_swedish_ci',
               is_default: true,
               maxlen: 1},
    15: {id: 15,
                name: 'latin1',
                collation: 'latin1_danish_ci',
                is_default: false,
                maxlen: 1},
    31: {id: 31,
                name: 'latin1',
                collation: 'latin1_german2_ci',
                is_default: false,
                maxlen: 1},
    47: {id: 47,
                name: 'latin1',
                collation: 'latin1_bin',
                is_default: false,
                maxlen: 1},
    48: {id: 48,
                name: 'latin1',
                collation: 'latin1_general_ci',
                is_default: false,
                maxlen: 1},
    49: {id: 49,
                name: 'latin1',
                collation: 'latin1_general_cs',
                is_default: false,
                maxlen: 1},
    94: {id: 94,
                name: 'latin1',
                collation: 'latin1_spanish_ci',
                is_default: false,
                maxlen: 1},
    2: {id: 2,
               name: 'latin2',
               collation: 'latin2_czech_cs',
               is_default: false,
               maxlen: 1},
    9: {id: 9,
               name: 'latin2',
               collation: 'latin2_general_ci',
               is_default: true,
               maxlen: 1},
    21: {id: 21,
                name: 'latin2',
                collation: 'latin2_hungarian_ci',
                is_default: false,
                maxlen: 1},
    27: {id: 27,
                name: 'latin2',
                collation: 'latin2_croatian_ci',
                is_default: false,
                maxlen: 1},
    77: {id: 77,
                name: 'latin2',
                collation: 'latin2_bin',
                is_default: false,
                maxlen: 1},
    30: {id: 30,
                name: 'latin5',
                collation: 'latin5_turkish_ci',
                is_default: true,
                maxlen: 1},
    78: {id: 78,
                name: 'latin5',
                collation: 'latin5_bin',
                is_default: false,
                maxlen: 1},
    20: {id: 20,
                name: 'latin7',
                collation: 'latin7_estonian_cs',
                is_default: false,
                maxlen: 1},
    41: {id: 41,
                name: 'latin7',
                collation: 'latin7_general_ci',
                is_default: true,
                maxlen: 1},
    42: {id: 42,
                name: 'latin7',
                collation: 'latin7_general_cs',
                is_default: false,
                maxlen: 1},
    79: {id: 79,
                name: 'latin7',
                collation: 'latin7_bin',
                is_default: false,
                maxlen: 1},
    38: {id: 38,
                name: 'macce',
                collation: 'macce_general_ci',
                is_default: true,
                maxlen: 1},
    43: {id: 43,
                name: 'macce',
                collation: 'macce_bin',
                is_default: false,
                maxlen: 1},
    39: {id: 39,
                name: 'macroman',
                collation: 'macroman_general_ci',
                is_default: true,
                maxlen: 1},
    53: {id: 53,
                name: 'macroman',
                collation: 'macroman_bin',
                is_default: false,
                maxlen: 1},
    13: {id: 13,
                name: 'sjis',
                collation: 'sjis_japanese_ci',
                is_default: true,
                maxlen: 2},
    88: {id: 88,
                name: 'sjis',
                collation: 'sjis_bin',
                is_default: false,
                maxlen: 2},
    10: {id: 10,
                name: 'swe7',
                collation: 'swe7_swedish_ci',
                is_default: true,
                maxlen: 1},
    82: {id: 82,
                name: 'swe7',
                collation: 'swe7_bin',
                is_default: false,
                maxlen: 1},
    18: {id: 18,
                name: 'tis620',
                collation: 'tis620_thai_ci',
                is_default: true,
                maxlen: 1},
    89: {id: 89,
                name: 'tis620',
                collation: 'tis620_bin',
                is_default: false,
                maxlen: 1},
    35: {id: 35,
                name: 'ucs2',
                collation: 'ucs2_general_ci',
                is_default: true,
                maxlen: 2},
    90: {id: 90,
                name: 'ucs2',
                collation: 'ucs2_bin',
                is_default: false,
                maxlen: 2},
    128: {id: 128,
                 name: 'ucs2',
                 collation: 'ucs2_unicode_ci',
                 is_default: false,
                 maxlen: 2},
    129: {id: 129,
                 name: 'ucs2',
                 collation: 'ucs2_icelandic_ci',
                 is_default: false,
                 maxlen: 2},
    130: {id: 130,
                 name: 'ucs2',
                 collation: 'ucs2_latvian_ci',
                 is_default: false,
                 maxlen: 2},
    131: {id: 131,
                 name: 'ucs2',
                 collation: 'ucs2_romanian_ci',
                 is_default: false,
                 maxlen: 2},
    132: {id: 132,
                 name: 'ucs2',
                 collation: 'ucs2_slovenian_ci',
                 is_default: false,
                 maxlen: 2},
    133: {id: 133,
                 name: 'ucs2',
                 collation: 'ucs2_polish_ci',
                 is_default: false,
                 maxlen: 2},
    134: {id: 134,
                 name: 'ucs2',
                 collation: 'ucs2_estonian_ci',
                 is_default: false,
                 maxlen: 2},
    135: {id: 135,
                 name: 'ucs2',
                 collation: 'ucs2_spanish_ci',
                 is_default: false,
                 maxlen: 2},
    136: {id: 136,
                 name: 'ucs2',
                 collation: 'ucs2_swedish_ci',
                 is_default: false,
                 maxlen: 2},
    137: {id: 137,
                 name: 'ucs2',
                 collation: 'ucs2_turkish_ci',
                 is_default: false,
                 maxlen: 2},
    138: {id: 138,
                 name: 'ucs2',
                 collation: 'ucs2_czech_ci',
                 is_default: false,
                 maxlen: 2},
    139: {id: 139,
                 name: 'ucs2',
                 collation: 'ucs2_danish_ci',
                 is_default: false,
                 maxlen: 2},
    140: {id: 140,
                 name: 'ucs2',
                 collation: 'ucs2_lithuanian_ci',
                 is_default: false,
                 maxlen: 2},
    141: {id: 141,
                 name: 'ucs2',
                 collation: 'ucs2_slovak_ci',
                 is_default: false,
                 maxlen: 2},
    142: {id: 142,
                 name: 'ucs2',
                 collation: 'ucs2_spanish2_ci',
                 is_default: false,
                 maxlen: 2},
    143: {id: 143,
                 name: 'ucs2',
                 collation: 'ucs2_roman_ci',
                 is_default: false,
                 maxlen: 2},
    144: {id: 144,
                 name: 'ucs2',
                 collation: 'ucs2_persian_ci',
                 is_default: false,
                 maxlen: 2},
    145: {id: 145,
                 name: 'ucs2',
                 collation: 'ucs2_esperanto_ci',
                 is_default: false,
                 maxlen: 2},
    146: {id: 146,
                 name: 'ucs2',
                 collation: 'ucs2_hungarian_ci',
                 is_default: false,
                 maxlen: 2},
    147: {id: 147,
                 name: 'ucs2',
                 collation: 'ucs2_sinhala_ci',
                 is_default: false,
                 maxlen: 2},
    148: {id: 148,
                 name: 'ucs2',
                 collation: 'ucs2_german2_ci',
                 is_default: false,
                 maxlen: 2},
    149: {id: 149,
                 name: 'ucs2',
                 collation: 'ucs2_croatian_ci',
                 is_default: false,
                 maxlen: 2},
    150: {id: 150,
                 name: 'ucs2',
                 collation: 'ucs2_unicode_520_ci',
                 is_default: false,
                 maxlen: 2},
    151: {id: 151,
                 name: 'ucs2',
                 collation: 'ucs2_vietnamese_ci',
                 is_default: false,
                 maxlen: 2},
    159: {id: 159,
                 name: 'ucs2',
                 collation: 'ucs2_general_mysql500_ci',
                 is_default: false,
                 maxlen: 2},
    12: {id: 12,
                name: 'ujis',
                collation: 'ujis_japanese_ci',
                is_default: true,
                maxlen: 3},
    91: {id: 91,
                name: 'ujis',
                collation: 'ujis_bin',
                is_default: false,
                maxlen: 3},
    54: {id: 54,
                name: 'utf16',
                collation: 'utf16_general_ci',
                is_default: true,
                maxlen: 4},
    55: {id: 55,
                name: 'utf16',
                collation: 'utf16_bin',
                is_default: false,
                maxlen: 4},
    101: {id: 101,
                 name: 'utf16',
                 collation: 'utf16_unicode_ci',
                 is_default: false,
                 maxlen: 4},
    102: {id: 102,
                 name: 'utf16',
                 collation: 'utf16_icelandic_ci',
                 is_default: false,
                 maxlen: 4},
    103: {id: 103,
                 name: 'utf16',
                 collation: 'utf16_latvian_ci',
                 is_default: false,
                 maxlen: 4},
    104: {id: 104,
                 name: 'utf16',
                 collation: 'utf16_romanian_ci',
                 is_default: false,
                 maxlen: 4},
    105: {id: 105,
                 name: 'utf16',
                 collation: 'utf16_slovenian_ci',
                 is_default: false,
                 maxlen: 4},
    106: {id: 106,
                 name: 'utf16',
                 collation: 'utf16_polish_ci',
                 is_default: false,
                 maxlen: 4},
    107: {id: 107,
                 name: 'utf16',
                 collation: 'utf16_estonian_ci',
                 is_default: false,
                 maxlen: 4},
    108: {id: 108,
                 name: 'utf16',
                 collation: 'utf16_spanish_ci',
                 is_default: false,
                 maxlen: 4},
    109: {id: 109,
                 name: 'utf16',
                 collation: 'utf16_swedish_ci',
                 is_default: false,
                 maxlen: 4},
    110: {id: 110,
                 name: 'utf16',
                 collation: 'utf16_turkish_ci',
                 is_default: false,
                 maxlen: 4},
    111: {id: 111,
                 name: 'utf16',
                 collation: 'utf16_czech_ci',
                 is_default: false,
                 maxlen: 4},
    112: {id: 112,
                 name: 'utf16',
                 collation: 'utf16_danish_ci',
                 is_default: false,
                 maxlen: 4},
    113: {id: 113,
                 name: 'utf16',
                 collation: 'utf16_lithuanian_ci',
                 is_default: false,
                 maxlen: 4},
    114: {id: 114,
                 name: 'utf16',
                 collation: 'utf16_slovak_ci',
                 is_default: false,
                 maxlen: 4},
    115: {id: 115,
                 name: 'utf16',
                 collation: 'utf16_spanish2_ci',
                 is_default: false,
                 maxlen: 4},
    116: {id: 116,
                 name: 'utf16',
                 collation: 'utf16_roman_ci',
                 is_default: false,
                 maxlen: 4},
    117: {id: 117,
                 name: 'utf16',
                 collation: 'utf16_persian_ci',
                 is_default: false,
                 maxlen: 4},
    118: {id: 118,
                 name: 'utf16',
                 collation: 'utf16_esperanto_ci',
                 is_default: false,
                 maxlen: 4},
    119: {id: 119,
                 name: 'utf16',
                 collation: 'utf16_hungarian_ci',
                 is_default: false,
                 maxlen: 4},
    120: {id: 120,
                 name: 'utf16',
                 collation: 'utf16_sinhala_ci',
                 is_default: false,
                 maxlen: 4},
    121: {id: 121,
                 name: 'utf16',
                 collation: 'utf16_german2_ci',
                 is_default: false,
                 maxlen: 4},
    122: {id: 122,
                 name: 'utf16',
                 collation: 'utf16_croatian_ci',
                 is_default: false,
                 maxlen: 4},
    123: {id: 123,
                 name: 'utf16',
                 collation: 'utf16_unicode_520_ci',
                 is_default: false,
                 maxlen: 4},
    124: {id: 124,
                 name: 'utf16',
                 collation: 'utf16_vietnamese_ci',
                 is_default: false,
                 maxlen: 4},
    56: {id: 56,
                name: 'utf16le',
                collation: 'utf16le_general_ci',
                is_default: true,
                maxlen: 4},
    62: {id: 62,
                name: 'utf16le',
                collation: 'utf16le_bin',
                is_default: false,
                maxlen: 4},
    60: {id: 60,
                name: 'utf32',
                collation: 'utf32_general_ci',
                is_default: true,
                maxlen: 4},
    61: {id: 61,
                name: 'utf32',
                collation: 'utf32_bin',
                is_default: false,
                maxlen: 4},
    160: {id: 160,
                 name: 'utf32',
                 collation: 'utf32_unicode_ci',
                 is_default: false,
                 maxlen: 4},
    161: {id: 161,
                 name: 'utf32',
                 collation: 'utf32_icelandic_ci',
                 is_default: false,
                 maxlen: 4},
    162: {id: 162,
                 name: 'utf32',
                 collation: 'utf32_latvian_ci',
                 is_default: false,
                 maxlen: 4},
    163: {id: 163,
                 name: 'utf32',
                 collation: 'utf32_romanian_ci',
                 is_default: false,
                 maxlen: 4},
    164: {id: 164,
                 name: 'utf32',
                 collation: 'utf32_slovenian_ci',
                 is_default: false,
                 maxlen: 4},
    165: {id: 165,
                 name: 'utf32',
                 collation: 'utf32_polish_ci',
                 is_default: false,
                 maxlen: 4},
    166: {id: 166,
                 name: 'utf32',
                 collation: 'utf32_estonian_ci',
                 is_default: false,
                 maxlen: 4},
    167: {id: 167,
                 name: 'utf32',
                 collation: 'utf32_spanish_ci',
                 is_default: false,
                 maxlen: 4},
    168: {id: 168,
                 name: 'utf32',
                 collation: 'utf32_swedish_ci',
                 is_default: false,
                 maxlen: 4},
    169: {id: 169,
                 name: 'utf32',
                 collation: 'utf32_turkish_ci',
                 is_default: false,
                 maxlen: 4},
    170: {id: 170,
                 name: 'utf32',
                 collation: 'utf32_czech_ci',
                 is_default: false,
                 maxlen: 4},
    171: {id: 171,
                 name: 'utf32',
                 collation: 'utf32_danish_ci',
                 is_default: false,
                 maxlen: 4},
    172: {id: 172,
                 name: 'utf32',
                 collation: 'utf32_lithuanian_ci',
                 is_default: false,
                 maxlen: 4},
    173: {id: 173,
                 name: 'utf32',
                 collation: 'utf32_slovak_ci',
                 is_default: false,
                 maxlen: 4},
    174: {id: 174,
                 name: 'utf32',
                 collation: 'utf32_spanish2_ci',
                 is_default: false,
                 maxlen: 4},
    175: {id: 175,
                 name: 'utf32',
                 collation: 'utf32_roman_ci',
                 is_default: false,
                 maxlen: 4},
    176: {id: 176,
                 name: 'utf32',
                 collation: 'utf32_persian_ci',
                 is_default: false,
                 maxlen: 4},
    177: {id: 177,
                 name: 'utf32',
                 collation: 'utf32_esperanto_ci',
                 is_default: false,
                 maxlen: 4},
    178: {id: 178,
                 name: 'utf32',
                 collation: 'utf32_hungarian_ci',
                 is_default: false,
                 maxlen: 4},
    179: {id: 179,
                 name: 'utf32',
                 collation: 'utf32_sinhala_ci',
                 is_default: false,
                 maxlen: 4},
    180: {id: 180,
                 name: 'utf32',
                 collation: 'utf32_german2_ci',
                 is_default: false,
                 maxlen: 4},
    181: {id: 181,
                 name: 'utf32',
                 collation: 'utf32_croatian_ci',
                 is_default: false,
                 maxlen: 4},
    182: {id: 182,
                 name: 'utf32',
                 collation: 'utf32_unicode_520_ci',
                 is_default: false,
                 maxlen: 4},
    183: {id: 183,
                 name: 'utf32',
                 collation: 'utf32_vietnamese_ci',
                 is_default: false,
                 maxlen: 4},
    33: {id: 33,
                name: 'utf8',
                collation: 'utf8_general_ci',
                is_default: true,
                maxlen: 3},
    83: {id: 83,
                name: 'utf8',
                collation: 'utf8_bin',
                is_default: false,
                maxlen: 3},
    192: {id: 192,
                 name: 'utf8',
                 collation: 'utf8_unicode_ci',
                 is_default: false,
                 maxlen: 3},
    193: {id: 193,
                 name: 'utf8',
                 collation: 'utf8_icelandic_ci',
                 is_default: false,
                 maxlen: 3},
    194: {id: 194,
                 name: 'utf8',
                 collation: 'utf8_latvian_ci',
                 is_default: false,
                 maxlen: 3},
    195: {id: 195,
                 name: 'utf8',
                 collation: 'utf8_romanian_ci',
                 is_default: false,
                 maxlen: 3},
    196: {id: 196,
                 name: 'utf8',
                 collation: 'utf8_slovenian_ci',
                 is_default: false,
                 maxlen: 3},
    197: {id: 197,
                 name: 'utf8',
                 collation: 'utf8_polish_ci',
                 is_default: false,
                 maxlen: 3},
    198: {id: 198,
                 name: 'utf8',
                 collation: 'utf8_estonian_ci',
                 is_default: false,
                 maxlen: 3},
    199: {id: 199,
                 name: 'utf8',
                 collation: 'utf8_spanish_ci',
                 is_default: false,
                 maxlen: 3},
    200: {id: 200,
                 name: 'utf8',
                 collation: 'utf8_swedish_ci',
                 is_default: false,
                 maxlen: 3},
    201: {id: 201,
                 name: 'utf8',
                 collation: 'utf8_turkish_ci',
                 is_default: false,
                 maxlen: 3},
    202: {id: 202,
                 name: 'utf8',
                 collation: 'utf8_czech_ci',
                 is_default: false,
                 maxlen: 3},
    203: {id: 203,
                 name: 'utf8',
                 collation: 'utf8_danish_ci',
                 is_default: false,
                 maxlen: 3},
    204: {id: 204,
                 name: 'utf8',
                 collation: 'utf8_lithuanian_ci',
                 is_default: false,
                 maxlen: 3},
    205: {id: 205,
                 name: 'utf8',
                 collation: 'utf8_slovak_ci',
                 is_default: false,
                 maxlen: 3},
    206: {id: 206,
                 name: 'utf8',
                 collation: 'utf8_spanish2_ci',
                 is_default: false,
                 maxlen: 3},
    207: {id: 207,
                 name: 'utf8',
                 collation: 'utf8_roman_ci',
                 is_default: false,
                 maxlen: 3},
    208: {id: 208,
                 name: 'utf8',
                 collation: 'utf8_persian_ci',
                 is_default: false,
                 maxlen: 3},
    209: {id: 209,
                 name: 'utf8',
                 collation: 'utf8_esperanto_ci',
                 is_default: false,
                 maxlen: 3},
    210: {id: 210,
                 name: 'utf8',
                 collation: 'utf8_hungarian_ci',
                 is_default: false,
                 maxlen: 3},
    211: {id: 211,
                 name: 'utf8',
                 collation: 'utf8_sinhala_ci',
                 is_default: false,
                 maxlen: 3},
    212: {id: 212,
                 name: 'utf8',
                 collation: 'utf8_german2_ci',
                 is_default: false,
                 maxlen: 3},
    213: {id: 213,
                 name: 'utf8',
                 collation: 'utf8_croatian_ci',
                 is_default: false,
                 maxlen: 3},
    214: {id: 214,
                 name: 'utf8',
                 collation: 'utf8_unicode_520_ci',
                 is_default: false,
                 maxlen: 3},
    215: {id: 215,
                 name: 'utf8',
                 collation: 'utf8_vietnamese_ci',
                 is_default: false,
                 maxlen: 3},
    223: {id: 223,
                 name: 'utf8',
                 collation: 'utf8_general_mysql500_ci',
                 is_default: false,
                 maxlen: 3},
    45: {id: 45,
                name: 'utf8mb4',
                collation: 'utf8mb4_general_ci',
                is_default: true,
                maxlen: 4},
    46: {id: 46,
                name: 'utf8mb4',
                collation: 'utf8mb4_bin',
                is_default: false,
                maxlen: 4},
    224: {id: 224,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_unicode_ci',
                 is_default: false,
                 maxlen: 4},
    225: {id: 225,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_icelandic_ci',
                 is_default: false,
                 maxlen: 4},
    226: {id: 226,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_latvian_ci',
                 is_default: false,
                 maxlen: 4},
    227: {id: 227,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_romanian_ci',
                 is_default: false,
                 maxlen: 4},
    228: {id: 228,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_slovenian_ci',
                 is_default: false,
                 maxlen: 4},
    229: {id: 229,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_polish_ci',
                 is_default: false,
                 maxlen: 4},
    230: {id: 230,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_estonian_ci',
                 is_default: false,
                 maxlen: 4},
    231: {id: 231,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_spanish_ci',
                 is_default: false,
                 maxlen: 4},
    232: {id: 232,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_swedish_ci',
                 is_default: false,
                 maxlen: 4},
    233: {id: 233,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_turkish_ci',
                 is_default: false,
                 maxlen: 4},
    234: {id: 234,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_czech_ci',
                 is_default: false,
                 maxlen: 4},
    235: {id: 235,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_danish_ci',
                 is_default: false,
                 maxlen: 4},
    236: {id: 236,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_lithuanian_ci',
                 is_default: false,
                 maxlen: 4},
    237: {id: 237,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_slovak_ci',
                 is_default: false,
                 maxlen: 4},
    238: {id: 238,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_spanish2_ci',
                 is_default: false,
                 maxlen: 4},
    239: {id: 239,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_roman_ci',
                 is_default: false,
                 maxlen: 4},
    240: {id: 240,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_persian_ci',
                 is_default: false,
                 maxlen: 4},
    241: {id: 241,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_esperanto_ci',
                 is_default: false,
                 maxlen: 4},
    242: {id: 242,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_hungarian_ci',
                 is_default: false,
                 maxlen: 4},
    243: {id: 243,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_sinhala_ci',
                 is_default: false,
                 maxlen: 4},
    244: {id: 244,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_german2_ci',
                 is_default: false,
                 maxlen: 4},
    245: {id: 245,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_croatian_ci',
                 is_default: false,
                 maxlen: 4},
    246: {id: 246,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_unicode_520_ci',
                 is_default: false,
                 maxlen: 4},
    247: {id: 247,
                 name: 'utf8mb4',
                 collation: 'utf8mb4_vietnamese_ci',
                 is_default: false,
                 maxlen: 4}
};


//    Lookup a character set by id
//
//    :returns: ``Charset`` instance if found
//    :throws: LookupError if no matching charset was found
function charsets_lookup(charset_id) {
    if (CHARSETS[charset_id]) {
        return CHARSETS[charset_id];
    } else {
        throw new Error("Charset id '${charset_id}' not found");
    }
}


